#!/usr/bin/lua

local util = require 'gluon.util'
local uci = require('luci.model.uci').cursor()
local site = require 'gluon.site_config'
local sysconfig = require 'gluon.sysconfig'

-- Initial
if not sysconfig.gluon_version then
  uci:delete_all('wireless', 'wifi-iface')
end

local function configure_radio(radio, index, config)
  if config then
    uci:delete('wireless', radio, 'disabled')

    uci:set('wireless', radio, 'channel', config.channel)
    uci:set('wireless', radio, 'htmode', 'HT20')
    uci:set('wireless', radio, 'country', site.regdom)
  end
end

util.iterate_radios(configure_radio)

uci:save('wireless')
uci:commit('wireless')
