#!/usr/bin/lua

local sysconfig = require 'gluon.sysconfig'

local fs = require 'luci.fs'
local util = require 'luci.util'


-- Save the Gluon version in the sysconfig so we know which version we
-- upgraded from after the next upgrade
sysconfig.gluon_version = util.trim(fs.readfile('/lib/gluon/gluon-version'))
