#!/usr/bin/lua

local uci = require('luci.model.uci').cursor()
local sysctl = require 'gluon.sysctl'


uci:set('network', 'wan', 'peerdns', '0')

uci:save('network')
uci:commit('network')


sysctl.set('net.ipv6.conf.all.accept_ra', 0)
sysctl.set('net.ipv6.conf.default.accept_ra', 0)
