#!/bin/sh

[ "$INTERFACE" = 'client' ] || exit 0

mkdir -p /var/gluon/mesh-batman-adv

for ns in $RDNSS $RA_DNS; do
	for domain in @mesh_domains@; do
		echo "server=/$domain/$ns"
	done
done > /var/gluon/mesh-batman-adv/dnsmasq.conf.$$

if cmp -s /var/gluon/mesh-batman-adv/dnsmasq.conf.$$ /var/gluon/mesh-batman-adv/dnsmasq.conf; then
	rm /var/gluon/mesh-batman-adv/dnsmasq.conf.$$
	exit 0
fi

lock /var/gluon/mesh-batman-adv/dnsmasq.conf.lock
mv -f /var/gluon/mesh-batman-adv/dnsmasq.conf.$$ /var/gluon/mesh-batman-adv/dnsmasq.conf
/etc/init.d/dnsmasq restart
lock -u /var/gluon/mesh-batman-adv/dnsmasq.conf.lock
