#!/bin/sh

. /lib/functions.sh
. /lib/gluon/functions/sysconfig.sh


uci_remove batman-adv bat0
uci_add batman-adv mesh bat0
uci_set batman-adv bat0 orig_interval '5000'
uci_set batman-adv bat0 gw_mode 'client'
uci_commit batman-adv

uci_remove network bat0
uci_add network interface bat0
uci_set network bat0 ifname 'bat0'
uci_set network bat0 proto 'none'
uci_set network bat0 macaddr "$(sysconfig primary_mac)"
uci_commit network

uci_remove firewall client
uci_add firewall zone client
uci_set firewall client name 'client'
uci add_list firewall.client.network='client'
uci_set firewall client input 'ACCEPT'
uci_set firewall client output 'ACCEPT'
uci_set firewall client forward 'REJECT'
uci_commit firewall

uci_remove dhcp client
uci_add dhcp dhcp client
uci_set dhcp client interface 'client'
uci_set dhcp client ignore '1'
uci_commit dhcp
