#!/usr/bin/lua

local util = require 'gluon.util'
local uci = require('luci.model.uci').cursor()
local site = require 'gluon.site_config'

local function configure_radio(radio, index, config)
  uci:delete('wireless', radio, 'disabled')

  uci:set('wireless', radio, 'channel', config.channel)
  uci:set('wireless', radio, 'htmode', config.htmode)
  uci:set('wireless', radio, 'country', site.regdom)
  uci:set('wireless', radio, 'iapp_interface', 'bat0')
end

util.iterate_radios(configure_radio)

uci:save('wireless')
uci:commit('wireless')
