#!/usr/bin/lua

local util = require 'gluon.util'
local uci = require('luci.model.uci').cursor()
local site = require 'gluon.site_config'

local function configure_radio(radio, index, config)
  uci:delete('wireless', radio, 'disabled')

  uci:set('wireless', radio, 'channel', config.channel)
  uci:set('wireless', radio, 'htmode', config.htmode)
  uci:set('wireless', radio, 'country', site.regdom)
  uci:set('wireless', radio, 'supported_rates', '6000 9000 12000 18000 24000 36000 48000 54000')
  uci:set('wireless', radio, 'basic_rate', '6000 9000 18000 36000 54000')
end

util.iterate_radios(configure_radio)

uci:save('wireless')
uci:commit('wireless')
