#!/usr/bin/lua

local site = require 'gluon.site_config'
local util = require 'gluon.util'
local uci = require 'luci.model.uci'

local c = uci.cursor()
local system = c:get_first('system', 'system')

c:set('system', system, 'hostname', site.hostname_prefix .. '-' .. util.node_id())
c:set('system', system, 'timezone', site.timezone)

c:save('system')
c:commit('system')
