#!/usr/bin/lua
local uci = require('luci.model.uci').cursor()

local sname = uci:get_first('gluon-node-info', 'location')
if sname then
  local options = {'longitude', 'latitude', 'altitude'}
  for _, option in ipairs(options) do
    local value = uci:get('gluon-node-info', sname, option)
    if value then
      uci:set('gluon-node-info', sname, option, value:trim())
    end
  end
  uci:save('gluon-node-info')
end
