#!/usr/bin/lua

local uci = require('simple-uci').cursor()

-- this hack directly uses the mesh interface as I haven't figured out teql and ddhcpd now and this shit should just work already

if uci:get('wireless', 'client_radio0', 'network') then
  uci:set('wireless', 'client_radio0', 'network', 'mesh_radio0')
  uci:save('wireless')
end
