#!/bin/sh

. /lib/functions/service.sh

ifname_to_dev () {
	ifstatus client "$1"|jsonfilter -e "@.device"
}

case "$ACTION" in
	ifup)   
		DEVICE="$(ifname_to_dev "$INTERFACE")"

		[ "$DEVICE" != "$(cat /lib/gluon/respondd/client.dev 2>/dev/null)" ] || 
			/etc/init.d/gluon-respondd restart_if_running &
		;;
esac
