#!/usr/bin/lua

local uci = require('luci.model.uci').cursor()
local site = require 'gluon.site_config'

uci:delete('network', 'l3roam')
uci:section('network', 'interface', 'l3roam',
{
	ifname = 'l3roam0',
	proto = 'none',
}
)

uci:delete('network', 'l3roamd_client')
uci:section('network', 'route6', 'l3roamd_client',
{
	interface = 'l3roam',
	target = site.prefix6,
	gateway = '::',
	table = '10',
}
)

uci:save('network')
