#!/usr/bin/lua

local site = require 'gluon.site'
local uci = require('simple-uci').cursor()
local unistd = require 'posix.unistd'

local has_tls = unistd.access('/lib/gluon/features/tls') ~= nil
local default_scheme = has_tls and 'https:' or 'http:'

local min_branch

local function mirror_urls(mirrors)
	local ret = {}

	for _, mirror in ipairs(mirrors) do
		if string.match(mirror, '^//') ~= nil then
			table.insert(ret, default_scheme .. mirror)
		else
			table.insert(ret, mirror)
		end
	end

	return ret
end

for name, config in pairs(site.autoupdater.branches()) do
	uci:delete('autoupdater', name)
	uci:section('autoupdater', 'branch', name, {
		name = config.name,
		mirror = mirror_urls(config.mirrors),
		good_signatures = config.good_signatures,
		pubkey = config.pubkeys,
	})

	if not min_branch or (name < min_branch) then
		min_branch = name
	end
end

local function default_branch()
	local f = io.open('/lib/gluon/autoupdater/default_branch')
	if f then
		local ret = f:read('*line')
		f:close()
		return ret
	end

	return site.autoupdater.branch(min_branch)
end

local enabled, branch
if not uci:get('autoupdater', 'settings') then
	enabled = unistd.access('/lib/gluon/autoupdater/default_enabled') ~= nil
end

local old_branch = uci:get('autoupdater', 'settings', 'branch')
if not old_branch or not uci:get('autoupdater', old_branch) then
	branch = default_branch()
	if not branch then
		enabled = false
	end
end

uci:section('autoupdater', 'autoupdater', 'settings', {
	enabled = enabled,
	branch = branch,
})

uci:set('autoupdater', 'settings', 'version_file', '/lib/gluon/release')

uci:save('autoupdater')


local urandom = io.open('/dev/urandom', 'r')
local seed1, seed2 = urandom:read(2):byte(1, 2)
math.randomseed(seed1*0x100 + seed2)
urandom:close()

-- Perform updates at a random time between 04:00 and 05:00, and once an hour
-- a fallback update (used after the regular updates haven't worked for
-- (priority+1) days after a firmware release, for example because the node
-- is always offline at night)
local minute = math.random(0, 59)

local f = io.open('/usr/lib/micron.d/autoupdater', 'w')
f:write(string.format('%i 4 * * * /usr/sbin/autoupdater\n', minute))
f:write(string.format('%i 0-3,5-23 * * * /usr/sbin/autoupdater --fallback\n', minute))
f:close()
