#!/bin/sh

setup_mode_enable() {
	local enabled configured
	enabled="$(uci -q get 'gluon-setup-mode.@setup_mode[0].enabled')"
	configured="$(uci -q get 'gluon-setup-mode.@setup_mode[0].configured')"

	if [ "$enabled" = 1 ] || [ "$configured" != 1 ]; then
		mount --bind /lib/gluon/setup-mode/procd-setup-mode /sbin/procd

		# This directory is a marker for scripts to know that we're
		# in config mode, but it is also used for temporary files
		mkdir -p /var/gluon/setup-mode
	fi
}

boot_hook_add preinit_main setup_mode_enable
