#!/bin/busybox sh
set -o pipefail

if ! out=$(batctl gwl -H 2>/dev/null); then
	# batctl gwl command failed
	exit 1
fi

if [[ -n "$out" ]]; then
	# no batctl gw available
	exit 2
fi

if ! batctl gw_mode | grep -q server; then
	# server is also not in gw_mode
	exit 3
fi
