#!/bin/sh /etc/rc.common

USE_PROCD=1
START=20
STOP=90

start_service() {
	procd_open_instance
	procd_set_param command /usr/sbin/gluon-arp-limiter
	procd_set_param respawn ${respawn_threshold:-3600} ${respawn_timeout:-5} ${respawn_retry:-5}

	procd_set_param env PATH=/usr/local/sbin:/usr/sbin:/usr/bin:/sbin:/bin
	procd_set_param stderr 1
	procd_close_instance
}
