#!/usr/bin/lua

local util = require 'gluon.util'
local uci = require('luci.model.uci').cursor()


-- fix up duplicate mac addresses (for mesh-on-WAN)
uci:set('network', 'wan', 'macaddr', util.generate_mac(3))
uci:save('network')

