#!/usr/bin/lua

local platform_info = require 'platform_info'
local sysconfig = require 'gluon.sysconfig'


if sysconfig.setup_ifname then
   os.exit(0)
end

if platform_info.get_board_name() == 'nanostation-m' then
   sysconfig.setup_ifname = sysconfig.config_ifname or sysconfig.wan_ifname or sysconfig.lan_ifname
else
   sysconfig.setup_ifname = sysconfig.config_ifname or sysconfig.lan_ifname or sysconfig.wan_ifname
end

-- Remove the old sysconfig setting
sysconfig.config_ifname = nil
