$(eval $(call GluonProfile,GENERIC))
$(eval $(call GluonProfileFactorySuffix,GENERIC))
$(eval $(call GluonProfileSysupgradeSuffix,GENERIC))
$(eval $(call GluonProfileExtraSuffix,GENERIC,.img.gz))
$(eval $(call GluonModel,GENERIC,combined-ext4,x86-generic))

$(eval $(call GluonProfile,VDI,kmod-pcnet32))
$(eval $(call GluonProfileFactorySuffix,VDI))
$(eval $(call GluonProfileSysupgradeSuffix,VDI))
$(eval $(call GluonProfileExtraSuffix,VDI,.vdi))
$(eval $(call GluonModel,VDI,combined-ext4,x86-virtualbox))

$(eval $(call GluonProfile,VMDK,kmod-pcnet32))
$(eval $(call GluonProfileFactorySuffix,VMDK))
$(eval $(call GluonProfileSysupgradeSuffix,VMDK))
$(eval $(call GluonProfileExtraSuffix,VMDK,.vmdk))
$(eval $(call GluonModel,VMDK,combined-ext4,x86-vmware))
