#!/usr/bin/lua

local site = require "gluon.site_config"

io.write("-i local-node -p " .. site.prefix6)

if site.dns and site.dns.servers and site.next_node and site.next_node.ip6 then
	io.write(" --rdnss " .. site.next_node.ip6)
end
