#!/usr/bin/lua

local site = require 'gluon.site_config'
local users = require 'gluon.users'
local util = require 'gluon.util'

local uci = require('simple-uci').cursor()


-- Group for iptables rule
users.add_group('gluon-tunneldigger', 900)

local enabled = uci:get('tunneldigger', 'mesh_vpn', 'enabled')
if enabled == nil then
	enabled = uci:get_first('tunneldigger', 'broker', 'enabled')
end
if enabled == nil then
	enabled = site.tunneldigger_mesh_vpn.enabled or false
end

-- Delete old broker config section       
if not uci:get('tunneldigger', 'mesh_vpn') then
	uci:delete_all('tunneldigger', 'broker')
end

uci:section('tunneldigger', 'broker', 'mesh_vpn',
	{
		enabled = enabled,
		uuid = util.node_id(),
		interface = 'mesh-vpn',
		bind_interface = 'br-wan',
		group = 'gluon-tunneldigger',
		broker_selection = 'usage',
		address = site.tunneldigger_mesh_vpn.brokers,
	}
)

uci:save('tunneldigger')

uci:section('network', 'interface', 'mesh_vpn',
	{
		ifname = 'mesh-vpn',
		proto = 'gluon_mesh',
		fixed_mtu = '1',
		transitive = '1',
		mtu = site.tunneldigger_mesh_vpn.mtu,
	}
)

uci:save('network')


uci:section('firewall', 'include', 'mesh_vpn_dns',
	{
		type = 'restore',
		path = '/lib/gluon/mesh-vpn-tunneldigger/iptables.rules',
		family = 'ipv4',
	}
)

uci:save('firewall')
