#!/usr/bin/lua

local site = require 'gluon.site'
local util = require 'gluon.util'
local vpn_core = require 'gluon.mesh-vpn'

local uci = require('simple-uci').cursor()


uci:section('tunneldigger', 'broker', 'mesh_vpn', {
	uuid = util.node_id(),
	interface = vpn_core.get_interface(),
	bind_interface = 'br-wan',
	group = 'gluon-mesh-vpn',
	broker_selection = 'usage',
	address = site.mesh_vpn.tunneldigger.brokers(),
})

uci:save('tunneldigger')
