#!/usr/bin/lua

local uci = require('simple-uci').cursor()
local site = require "gluon.site"

uci:section('firewall', 'zone', 'mmfd', {
	name = 'mmfd',
	input = 'REJECT',
	output = 'accept',
	forward = 'REJECT',
	device = 'mmfd+',
	log = '1',
})

uci:section('firewall', 'rule',  'mesh_mmfd', {
	src = 'mesh',
	src_ip = 'fe80::/64',
	dest_port = '27275',
	proto = 'udp',
	target = 'ACCEPT',
})

uci:section('firewall', 'rule',  'mesh_respondd_mcast_ll', {
	src = 'mesh',
	src_ip = 'fe80::/64' ,
	dest_port = '1001',
	proto = 'udp',
	target = 'ACCEPT',
})

uci:section('firewall', 'rule',  'mesh_respondd_mcast2', {
	src = 'mesh',
	src_ip = site.node_prefix6() or site.prefix6(),
	dest_port = '1001',
	proto = 'udp',
	target = 'ACCEPT',
})

uci:section('firewall', 'rule',  'mmfd_respondd_ll', {
	src = 'mmfd',
	src_ip = 'fe80::/64',
	dest_port = '1001',
	proto = 'udp',
	target = 'ACCEPT',
})

uci:section('firewall', 'rule',  'mmfd_respondd_mesh', {
	src = 'mmfd',
	src_ip = site.node_prefix6() or site.prefix6(),
	dest_port = '1001',
	proto = 'udp',
	target = 'ACCEPT',
})

-- the flood carries the same respondd queries as the mesh, so the asker can
-- be in any prefix the mesh zone accepts (see 400-respondd-firewall)
uci:delete_all('firewall', 'rule', function(rule)
	return rule['.name']:find('^mmfd_respondd_extraprefix')
end)

for idx, prefix in ipairs(site.extra_prefixes6({})) do
	uci:section('firewall', 'rule',  'mmfd_respondd_extraprefix' .. idx, {
		src = 'mmfd',
		src_ip = prefix,
		dest_port = '1001',
		proto = 'udp',
		target = 'ACCEPT',
	})
end

uci:save('firewall')
