#!/usr/bin/lua

local uci = require('simple-uci').cursor()
uci:section('firewall', 'include', 'vpn_clamp_mss', {
	type = 'nftables',
	position = 'chain-prepend',
	chain = 'mangle_forward',
	path = '/lib/gluon/mesh-vpn/nftables-mss.rules',
})

uci:save('firewall')
