#!/usr/bin/lua

local site = require 'gluon.site'
local uci = require('simple-uci').cursor()


if site.setup_mode.skip(false) and not uci:get_first('gluon-setup-mode', 'setup_mode', 'configured', false) then
	local name = uci:get_first("gluon-setup-mode", "setup_mode")
	uci:set("gluon-setup-mode", name, "configured", true)
	uci:save('gluon-setup-mode')
end
