#!/usr/bin/lua

local platform = require 'gluon.platform'
local sysconfig = require 'gluon.sysconfig'

if platform.is_outdoor_device() or
	platform.match('ath79', 'generic', {
		'ubnt,unifi-ap-pro',
		'ubnt,unifiac-pro',
	})
then
	sysconfig.setup_ifname = sysconfig.single_ifname or sysconfig.wan_ifname
else
	sysconfig.setup_ifname = sysconfig.single_ifname or sysconfig.lan_ifname
end
