#!/usr/bin/lua

local platform = require 'gluon.platform'
local sysconfig = require 'gluon.sysconfig'

if platform.is_outdoor_device() then
	sysconfig.setup_ifname = sysconfig.single_ifname or sysconfig.wan_ifname
else
	sysconfig.setup_ifname = sysconfig.single_ifname or sysconfig.lan_ifname
end
