#!/bin/sh


has_root_pwd() {
	local pwd=$([ -f "$1" ] && cat "$1")
	pwd="${pwd#*root:}"
	pwd="${pwd%%:*}"

	test -n "${pwd#[\!x]}"
}


has_root_pwd /etc/passwd || has_root_pwd /etc/shadow || passwd -l root
