#!/usr/bin/lua

local site = require 'gluon.site_config'
local sysconfig = require 'gluon.sysconfig'

local uci = require('luci.model.uci').cursor()


if sysconfig.gluon_version == 'legacy' then
  for _, config in ipairs(site.legacy.tc_configs) do
    local s = uci:get_first(config, 'bandwidth')
    if s then
      old = uci:get_all(config, s)
      uci:section('simple-tc', 'interface', 'mesh_vpn',
		{
		  ifname = 'mesh-vpn',
		  enabled = old.enabled,
		  limit_ingress = old.downstream,
		  limit_egress = old.upstream,
		}
      )

      uci:save('simple-tc')
      uci:commit('simple-tc')

      break
    end
  end
end
