#!/bin/sh /etc/rc.common

EXTRA_COMMANDS='restart_if_running'

USE_PROCD=1
START=50

DEVLIST=/var/run/gluon-respondd.devs
DAEMON=/usr/bin/respondd


start_service() {
	DEVS=$(cat $DEVLIST 2>/dev/null | while read dev iface; do echo -n " -i $dev"; done)
	procd_open_instance
	procd_set_param command $DAEMON -g ff02::2:1001 -p 1001 -d /lib/gluon/respondd $DEVS
	procd_set_param respawn ${respawn_threshold:-3600} ${respawn_timeout:-5} ${respawn_retry:-5}
	procd_set_param stderr 1
	procd_close_instance
}

restart_if_running() {
	if service_check $DAEMON; then
		stop
		start
	fi
}
