#!/bin/sh

. /lib/functions.sh
. /lib/gluon/functions/sysconfig.sh

macaddr=$(sysconfig primary_mac)

uci_set system '@system[0]' hostname "@hostname_prefix@-${macaddr//:/}"
uci_set system '@system[0]' timezone '@timezone@'
uci_commit system
