#!/usr/bin/lua

local site = require 'gluon.site_config'
local uci = require 'luci.model.uci'

local c = uci.cursor()


for _, config in ipairs(site.legacy.config_mode_configs) do
	local old = c:get_first(config, 'wizard', 'configured')
	if old == '1' then
		local setup_mode = c:get_first('gluon-setup-mode', 'setup_mode')
		c:set('gluon-setup-mode', setup_mode, 'configured', '1')

		c:save('gluon-setup-mode')
		c:commit('gluon-setup-mode')

		break
	end
end
