#!/bin/sh

. /lib/functions.sh

config_load wireless

delete_legacy_iface() {
	local iface="$1"

	for wifi in @legacy.wifi_names@; do
		if [ "$wifi" =  "$iface" ]; then
			uci_remove wireless "$iface"
			break
		fi
	done
}

config_foreach delete_legacy_iface 'wifi-iface'
uci_commit wireless
