#!/bin/sh

. /lib/functions.sh
. /lib/gluon/functions/sysconfig.sh


uci_remove batman-adv bat0
uci_add batman-adv mesh bat0
uci_set batman-adv bat0 orig_interval '5000'
uci_set batman-adv bat0 gw_mode 'client'
uci_commit batman-adv

uci_add network interface client
uci_set network client ifname "$(sysconfig lan_ifname) bat0"
uci_set network client type 'bridge'
uci_set network client proto 'dhcpv6'
uci_set network client reqprefix 'no'
uci_set network client peerdns '0'
uci_set network client macaddr "$(sysconfig primary_mac)"

uci_add network interface bat0
uci_set network bat0 ifname 'bat0'
uci_set network bat0 proto 'none'
uci_set network bat0 macaddr "$(sysconfig primary_mac)"
uci_commit network

uci_add firewall zone client
uci_set firewall client name 'client'
uci add_list firewall.client.network='client'
uci_set firewall client input 'ACCEPT'
uci_set firewall client output 'ACCEPT'
uci_set firewall client forward 'REJECT'
uci_commit firewall

uci_add dhcp dhcp client
uci_set dhcp client interface 'client'
uci_set dhcp client ignore '1'
uci_commit dhcp

echo 'net.ipv6.conf.br-client.forwarding=0' >> /etc/sysctl.conf
