#!/usr/bin/lua

util = require 'luci.util'
json = require 'luci.jsonc'
fs = require 'nixio.fs'
mesh = require 'gluon.mesh'

io.write("Access-Control-Allow-Origin: *\n")
io.write("Content-type: application/json\n\n")

interfaces = {}

for interface, _ in ipairs(mesh.interfaces()) do
  if ifname ~= nil then
    pcall(function()
      local address = util.trim(fs.readfile('/sys/class/net/' .. ifname .. '/address'))
      interfaces[ifname] = { address = address }
    end)
  end
end

io.write(json.stringify(interfaces))
