include $(TOPDIR)/rules.mk

PKG_NAME:=gluon-mesh-layer3-common

include ../gluon.mk

define Package/gluon-mesh-layer3-common
  TITLE:=Layer3 common files
  DEPENDS:=+gluon-core +gluon-mmfd +firewall4
endef

$(eval $(call BuildPackageGluon,gluon-mesh-layer3-common))
