#!/bin/sh /etc/rc.common

START=15


boot() {
	local enabled="$(uci -q get 'gluon-setup-mode.@setup_mode[0].enabled')"
	local configured="$(uci -q get 'gluon-setup-mode.@setup_mode[0].configured')"

	uci set 'gluon-setup-mode.@setup_mode[0].enabled=0'
	uci commit gluon-setup-mode

	if [ "$enabled" != 1 -a "$configured" = 1 ]; then
		# This can happen after an upgrade from a version before the config file was called gluon-setup-mode
		# We'll just reboot to return to the normal mode...
		/etc/init.d/done boot
		reboot
	fi
}
