#!/bin/sh /etc/rc.common

USE_PROCD=1
PROG=/usr/sbin/dropbear
NAME=dropbear

start_service() {
	[ -x /etc/init.d/dropbear ] || return 0

	. /etc/init.d/dropbear

	[ -s /etc/dropbear/dropbear_rsa_host_key ] || keygen

	. /lib/functions.sh
	. /lib/functions/network.sh

	procd_open_instance
	procd_set_param command "$PROG" -F -f
	procd_set_param respawn
	procd_close_instance
}
