#!/usr/bin/lua

local site = require 'gluon.site_config'
local uci = require('simple-uci').cursor()
local config = 'geolocator'
local refresh_interval = uci:get(config, uci:get_first(config, 'settings'), 'refresh_interval')

local default_refresh_interval = 43200 --12h
if site.config_mode.geolocator.interval then
  default_refresh_interval = tonumber(site.config_mode.geolocator.interval)
end

if not refresh_interval then
  uci:set(config, uci:get_first(config, 'settings'), 'refresh_interval', default_refresh_interval)
  uci:save(config)
end

