#!/usr/bin/lua

local site = require 'gluon.site'
local uci = require('simple-uci').cursor()

local config = 'geolocator'

local static_location = uci:get(config, 'settings', 'static_location')

local auto_location = uci:get(config, 'settings', 'auto_location')
if not auto_location then
	auto_location = site.geolocator.autolocation(false)
end

uci:delete(config, 'settings')
uci:section(config, config, 'settings', {
	static_location = static_location,
	auto_location = auto_location,
})

local refresh_interval = site.geolocator.interval(12) -- default: 12h

local f = io.open('/usr/lib/micron.d/geolocator', 'w')
f:write(string.format('* */%i * * *     /lib/gluon/geolocator/geolocator\n', refresh_interval))
f:close()
uci:save(config)
