#!/usr/bin/lua

local site = require 'gluon.site'
local uci = require('simple-uci').cursor()

local config = 'geolocator'

local static_location = uci:get(config, 'settings', 'static_location')

local auto_location = uci:get(config, 'settings', 'auto_location')
if not auto_location then
	auto_location = site.geolocator.autolocation(false)
end

local refresh_interval = uci:get(config, 'settings', 'refresh_interval')
if not refresh_interval then
	refresh_interval = site.geolocator.interval(720) -- default: 12h
end

uci:delete(config, 'settings')
uci:section(config, config, 'settings', {
	static_location = static_location,
	refresh_interval = refresh_interval,
	auto_location = auto_location,
})
uci:save(config)
