#!/usr/bin/lua

local sysconfig = require 'gluon.sysconfig'
local site = require 'gluon.site_config'

local uci = require('luci.model.uci').cursor()


local gw_sel_class
if site.mesh and site.mesh.batman_adv then
	gw_sel_class = site.mesh.batman_adv.gw_sel_class
end

uci:delete('batman-adv', 'bat0')
uci:section('batman-adv', 'mesh', 'bat0',
	{
		orig_interval = 5000,
		gw_mode = 'client',
		gw_sel_class = gw_sel_class,
		hop_penalty = 15,
		multicast_mode = 0,
	}
)
uci:save('batman-adv')

uci:delete('network', 'bat0')
uci:section('network', 'interface', 'bat0',
	{
		ifname = 'bat0',
		proto = 'none',
		macaddr = sysconfig.primary_mac,
		multicast_router = 2,
		learning = 0,
	}
)

uci:add_to_set('network', 'client', 'ifname', 'bat0')

uci:save('network')
