#!/usr/bin/lua

-- This script must be ordered after 310-gluon-client-bridge-local-node, as
-- it overrides parts of network.local_node


local site = require 'gluon.site_config'
local sysconfig = require 'gluon.sysconfig'
local sysctl = require 'gluon.sysctl'

local uci = require('simple-uci').cursor()


uci:section('network', 'interface', 'local_node', {
	proto = 'dhcpv6',
	reqprefix = 'no',
	peerdns = not (site.dns and site.dns.servers),
	sourcefilter = false,
	keep_ra_dnslifetime = true,
})

uci:delete('network', 'local_node_route6')
uci:section('network', 'route6', 'local_node_route6', {
	interface = 'local-node',
	target = site.prefix6,
	gateway = '::',
})

uci:save('network')


uci:delete('firewall', 'local_node')
uci:section('firewall', 'zone', 'local_node', {
	name = 'local_node',
	network = {'local_node'},
	input = 'ACCEPT',
	output = 'ACCEPT',
	forward = 'REJECT',
})

uci:section('firewall', 'rule', 'local_node_dns', {
	name = 'local_node_dns',
	src = 'local_node',
	dest_port = '53',
	target = 'REJECT',
})

uci:save('firewall')


sysctl.set('net.ipv6.conf.local_node.forwarding', 0)
