#!/usr/bin/lua

local uci = require('luci.model.uci').cursor()

if uci:get('system', 'rssid_wlan0') then
  if uci:get('wireless', 'mesh_radio0') then
    uci:set('system', 'rssid_wlan0', 'dev', 'mesh0')
  else
    uci:set('system', 'rssid_wlan0', 'dev', 'ibss0')
  end

  uci:save('system')
end
