include $(TOPDIR)/rules.mk

PKG_NAME:=gluon-private-ap

include ../gluon.mk

define Package/gluon-private-ap
  TITLE:=Provides a virtual access point for the nodes client network
  DEPENDS:=+gluon-core
endef

$(eval $(call BuildPackageGluon,gluon-private-ap))
