#!/bin/sh /etc/rc.common

. $IPKG_INSTROOT/lib/functions/network.sh

START=70

pidfile='/var/run/babeld.pid'
CONFIGFILE='/var/etc/gluon-babel.conf'
EXTRA_COMMANDS="status"
EXTRA_HELP="        status Dump Babel's table to the log file."

start() {
  mkdir -p /var/lib
  mkdir -p /var/etc

  /lib/gluon/gluon-mesh-babel/mkconfig "$CONFIGFILE"
  /usr/sbin/babeld -D -I "$pidfile" -c "$CONFIGFILE"
  # Wait for the pidfile to appear
  for i in 1 2
  do
    [ -f "$pidfile" ] || sleep 1
  done
  [ -f "$pidfile" ] || (echo "Failed to start babeld"; exit 42)
}

stop() {
  [ -f "$pidfile" ] && kill $(cat $pidfile)
  # avoid race-condition on restart: wait for
  # babeld to die for real.
  [ -f "$pidfile" ] && sleep 1
  [ -f "$pidfile" ] && sleep 1
  [ -f "$pidfile" ] && sleep 1
  [ -f "$pidfile" ] && exit 42
}

status() {
  [ -f "$pidfile" ] && kill -USR1 $(cat $pidfile)
}
