include $(TOPDIR)/rules.mk

PKG_NAME:=gluon-yggdrasil

include ../gluon.mk

define Package/gluon-yggdrasil
  TITLE:=yggdrasil integration
  DEPENDS:=+gluon-core +yggdrasil
endef


$(eval $(call BuildPackageGluon,gluon-yggdrasil))
