include $(TOPDIR)/rules.mk

PKG_NAME:=gluon-config-mode-hostname
PKG_VERSION:=1

include ../gluon.mk

define Package/gluon-config-mode-hostname
  TITLE:=Set the hostname
  DEPENDS:=+gluon-config-mode-core
endef

$(eval $(call BuildPackageGluon,gluon-config-mode-hostname))
