#!/usr/bin/lua 
local mesh = require 'gluon.mesh' 
local querystring = os.getenv("QUERY_STRING") 

print('Access-Control-Allow-Origin: *\n') 

for interface, _ in pairs(mesh.interfaces()) do 
  if querystring 
  then 
    if string.find(interface, querystring) 
    then 
      os.execute("/usr/bin/gluon-neighbour-info -s neighbour -i " .. querystring .. " -d ff02::2:1001 -p 1001 -r nodeinfo"); 
      os.exit(0) 
    end 
  end 
end 

print("Status: 400 Bad Request\n") 
os.exit(1) 
