#!/bin/sh

echo 'Access-Control-Allow-Origin: *'

batctl if | cut -d: -f1 | grep -qxF "$QUERY_STRING" || exit 1

exec /usr/bin/gluon-neighbour-info -s neighbour -i "$QUERY_STRING" -d ff02::2:1001 -p 1001 -r nodeinfo
