#!/usr/bin/lua 
local mesh = require 'gluon.mesh' 
local querystring = os.getenv("QUERY_STRING") 

print('Access-Control-Allow-Origin: *\n') 

for interface, _ in pairs(mesh.interfaces()) do 
  if querystring 
  then 
    if string.find(interface, querystring) 
    then 
      os.execute("/usr/sbin/sse-multiplex /lib/gluon/status-page/providers/stations " .. querystring ); 
      os.exit(0) 
    end 
  end 
end 


print("Status: 400 Bad Request\n") 
os.exit(1) 
