#!/bin/sh

badrequest() {
        echo 'Status: 400 Bad Request'
        echo
        exit 1
}

echo 'Access-Control-Allow-Origin: *'

lua -e 'mesh = require(gluon.mesh); for interface, _ in ipairs(mesh.interfaces()) do print(interface .. "\n"); end;' | grep -qxF "$QUERY_STRING" || badrequest

CMD="exec /lib/gluon/status-page/providers/stations '$QUERY_STRING'"

exec /usr/sbin/sse-multiplex "$CMD"
