#!/usr/bin/lua
local site = require "gluon.site"

io.write("-i local-node --default-lifetime 900 -a " .. site.prefix6())
if site.dns() and site.dns.servers() then
	io.write(" --rdnss " .. site.next_node.ip6())
end
if site.uradvd() then
	if site.uradvd.preferred_lifetime() then
		io.write(" --preferred-lifetime " .. site.uradvd.preferred_lifetime())
	end
	if site.uradvd.valid_lifetime() then
		io.write(" --valid-lifetime " .. site.uradvd.valid_lifetime())
	end
end
