#!/bin/sh

uci batch <<-EOF
	delete uhttpd.main.listen_http
	add_list uhttpd.main.listen_http=0.0.0.0:80
	add_list uhttpd.main.listen_http=[::]:80

	delete uhttpd.main.listen_https

	set uhttpd.main.home=/lib/gluon/status-page/www

	set uhttpd.main.max_requests=32

	commit uhttpd
EOF
