include $(TOPDIR)/rules.mk

PKG_NAME:=gluon-web-cellular

include ../gluon.mk

define Package/gluon-web-cellular
  DEPENDS:=+gluon-web-admin
  TITLE:=UI for activating cellular WAN
endef

$(eval $(call BuildPackageGluon,gluon-web-cellular))
