#!/usr/bin/lua

local site = require 'gluon.site_config'
local uci = require 'luci.model.uci'

if site.next_node then
  local c = uci.cursor()

  c:delete('firewall', 'local_node')
  c:section('firewall', 'zone', 'local_node',
      {
        name = 'local_node',
        network = {'local_node'},
        input = 'ACCEPT',
        output = 'ACCEPT',
        forward = 'REJECT',
      }
  )

  c:delete('network', 'local_node_route6')
  c:section('network', 'route6', 'local_node_route6',
      {
        interface = 'client',
        target = site.prefix6,
        gateway = '::',
      }
  )

  c:delete('network', 'local_node_route4')
  c:section('network', 'route6', 'local_node_route4',
      {
        interface = 'client',
        target = site.prefix4,
        gateway = '0.0.0.0',
      }
  )

  c:save('firewall')
  c:save('firewall')
  c:save('network')
  c:commit('firewall')
  c:commit('network')
end
