#!/usr/bin/lua

local sysconfig = require 'gluon.sysconfig'

local uci = require('simple-uci').cursor()


uci:delete('network', 'local_node_dev')
uci:section('network', 'device', 'local_node_dev', {
	name = 'local-node',
	ifname = 'br-client',
	type = 'macvlan',
	macaddr = sysconfig.primary_mac,
})

uci:delete('network', 'local_node')
uci:section('network', 'interface', 'local_node', {
	ifname = 'local-node',
	proto = 'none',
	auto = true,
})

uci:save('network')


uci:delete('dhcp', 'local_node')
uci:section('dhcp', 'dhcp', 'local_node', {
	interface = 'local_node',
	ignore = true,
})

uci:save('dhcp')
