#!/bin/sh /etc/rc.common

START=99

SERVICE_NAME=gluon-autoupdater
SERVICE_WRITE_PID=1
SERVICE_DAEMONIZE=1


start() {
	[ "$(uci get autoupdater.settings.enabled)" = 1 ] || return

	service_start /bin/sh /lib/gluon/autoupdater/delayed_update
}

stop() {
	service_stop /bin/sh
}
