include $(TOPDIR)/rules.mk

PKG_NAME:=gluon-config-mode-outdoor
PKG_VERSION:=1

include ../gluon.mk

define Package/gluon-config-mode-outdoor
  TITLE:=UI for displaying & changing the outdoor mode flag in the wizard
  DEPENDS:=+gluon-config-mode-core
endef

$(eval $(call BuildPackageGluon,gluon-config-mode-outdoor))
