#!/usr/bin/lua


local site = require 'gluon.site_config'
local uci = require 'luci.model.uci'


local c = uci.cursor()


function delete_legacy_iface(iface)
	for _, wifi in pairs(site.legacy.wifi_names) do
		if wifi == iface['.name'] then
			return true
		end
	end

	return false
end

c:delete_all('wireless', 'wifi-iface', delete_legacy_iface)

c:save('wireless')
c:commit('wireless')
