#!/usr/bin/lua

local sysconfig = require 'gluon.sysconfig'
local util = require 'gluon.util'

local uci = require('simple-uci').cursor()


local gw_mode = uci:get('network', 'gluon_bat0', 'gw_mode') or uci:get('network', 'bat0', 'gw_mode') or 'client'

uci:delete('batman-adv-legacy', 'bat0')
uci:save('batman-adv-legacy')

uci:delete('batman-adv', 'bat0')
uci:save('batman-adv')

uci:delete('network', 'gluon_bat0')
uci:section('network', 'interface', 'gluon_bat0', {
	proto = 'gluon_bat0',
	gw_mode = gw_mode,
})

uci:delete('network', 'bat0')
uci:section('network', 'interface', 'bat0', {
	ifname = 'bat0',
	proto = 'none',
	auto = true,
	macaddr = sysconfig.primary_mac,
	multicast_router = 2,
	learning = true,
})

local interfaces = uci:get_list('network', 'client', 'ifname')
util.add_to_set(interfaces, 'bat0')
uci:set_list('network', 'client', 'ifname', interfaces)

uci:save('network')
