#!/usr/bin/lua

-- This script must be ordered after 300-gluon-client-bridge-network, as
-- it overrides parts of network.client


local site = require 'gluon.site'
local sysconfig = require 'gluon.sysconfig'
local util = require 'gluon.util'
local uci = require('simple-uci').cursor()
local next_node = site.next_node({})


uci:section('network', 'interface', 'client', {
	ipv6 = true,
	proto = 'dhcpv6',
	reqprefix = 'no',
	peerdns = not site.dns.servers(),
	sourcefilter = false,
	keep_ra_dnslifetime = true,
	robustness = 9,
	query_interval = 2000,
	query_response_interval = 500,
})

uci:delete('network', 'client_lan')

uci:section('network', 'route', 'br_client_route', {
	interface = 'client',
	target = site.prefix4(),
})

uci:section('network', 'rule', 'local_node_rule', {
	src = next_node.ip4 .. '/32',
	lookup = 2,
})
uci:set('network', 'local_node_rule', 'in', 'loopback')

uci:delete('network', 'local_node_route')
uci:section('network', 'route', 'local_node_route', {
	interface = 'local_node',
	target = site.prefix4(),
	table = 2,
})

uci:section('network', 'rule6', 'local_node_rule6', {
	src = next_node.ip6 .. '/128',
	lookup = 2,
})
uci:set('network', 'local_node_rule6', 'in', 'loopback')

uci:delete('network', 'local_node_route6')
uci:section('network', 'route6', 'local_node_route6', {
	interface = 'local_node',
	target = site.prefix6(),
	table = 2,
})

uci:save('network')

local networks = uci:get_list('firewall', 'mesh', 'network')
util.add_to_set(networks, 'client')
uci:set_list('firewall', 'mesh', 'network', networks)

local networks = uci:get_list('firewall', 'drop', 'network')
util.remove_from_set(networks, 'client')
uci:set_list('firewall', 'drop', 'network', networks)

uci:delete('firewall', 'local_node_dns')

uci:save('firewall')
