#!/usr/bin/lua

local bit = require('bit')
local unistd = require('posix.unistd')
local fcntl = require('posix.fcntl')
local hoodutil = require('hoodselector.util')

-- PID file to ensure the hoodselector isn't running parallel
local lockfile = '/var/lock/hoodselector.lock'
local lockfd, err = fcntl.open(lockfile, bit.bor(fcntl.O_WRONLY, fcntl.O_CREAT), 384) -- mode 0600

if not lockfd then
  hoodutil.log(err, '\n')
  os.exit(1)
end

local ok, _ = fcntl.fcntl(lockfd, fcntl.F_SETLK, {
  l_start = 0,
  l_len = 0,
  l_type = fcntl.F_WRLCK,
  l_whence = unistd.SEEK_SET,
})

if not ok then
  io.stderr:write(string.format(
    "Unable to lock file %s. Make sure there is no other instance of the hoodselector running.\n",
    lockfile
  ))
  os.exit(1)
end

-- VPN MODE
-- If we have a VPN connection we will try to get the node's location and
-- select the hood coresponding to this location.
-- If no hood for the location has been defined, we will select
-- the default hood.
-- If we can't determine the node's location, we will continue to the next mode.
if hoodutil.direct_vpn() then
  io.stdout:write('VPN connection found.\n')
  local geo = hoodutil.get_geolocation()
  if geo.lat ~= nil and geo.lon ~= nil then
    io.stdout:write('Position found.\n')
    local jhood = hoodutil.get_domains()
    local geo_hood = hoodutil.get_hood_by_geo(jhood, geo)
    if geo_hood ~= nil then
      if hoodutil.set_hoodconfig(geo_hood) then
        hoodutil.restart_services()
        hoodutil.log('Domain set by VPN mode.\n')
      end
      return
    end
    io.stdout:write('No domain has been defined for the current position.\n')
    if hoodutil.set_hoodconfig(hoodutil.get_default_hood(jhood)) then
      hoodutil.restart_services()
      hoodutil.log('Domain set by VPN mode.\n')
    end
    return
  else
    -- The hoodselector should continue with the next states because there can be other
    -- VPN nodes in the local mesh network which provide a position and therefore
    -- have set a geo base hood.
    io.stdout:write('No position found\n')
  end
else
  io.stdout:write('No VPN connection found\n')
end
