#!/usr/bin/lua

local site = require 'gluon.site'
local file = '/etc/dropbear/authorized_keys'

local keys = {}
local rm_keys = {}

local function load_keys()
	for line in io.lines(file) do
		keys[line] = true
	end
end

for _, key in ipairs(site.unauthorized_keys({})) do
	rm_keys[key] = true
end

pcall(load_keys)

local f = io.open(file, 'w')
for _, key in ipairs(site.authorized_keys()) do
	if not keys[key] then
		f:write(key .. '\n')
	end
end
for key, _ in pairs(keys) do
	if not rm_keys[key] then
		f:write(key .. '\n')
	end
end
f:close()
