#pragma once

/* Seconds*/
#define REMOTE_SETUP_MODE_RX_TIMEOUT						5
#define REMOTE_SETUP_MODE_TX_INTERVAL						1

#define REMOTE_SETUP_MODE_MAC_LEN						6
#define REMOTE_SETUP_MODE_DST_MAC_OFFSET					0
#define REMOTE_SETUP_MODE_DST_MAC						0x01, 0x80, 0xc2, 0x00, 0x00, 0x0e
#define REMOTE_SETUP_MODE_SRC_MAC_OFFSET					6
#define REMOTE_SETUP_MODE_SRC_MAC						0xda, 0xec, 0xe5, 0x8f, 0x60, 0x14

#define REMOTE_SETUP_MODE_ETHERTYPE_OFFSET					(REMOTE_SETUP_MODE_MAC_LEN + REMOTE_SETUP_MODE_MAC_LEN)
#define REMOTE_SETUP_MODE_ETHERTYPE_LEN						2
#define REMOTE_SETUP_MODE_ETHERTYPE						0x23, 0x42

#define REMOTE_SETUP_MODE_DATA_CMD_OFFSET					(REMOTE_SETUP_MODE_ETHERTYPE_OFFSET + REMOTE_SETUP_MODE_ETHERTYPE_LEN)
#define REMOTE_SETUP_MODE_DATA_CMD_SETUP					"SETUP"
