#!/bin/sh


uci rename fastd.ffhl_mesh_vpn=mesh_vpn


bind="$(uci -q get fastd.mesh_vpn.bind)"
uci -q delete fastd.mesh_vpn.bind

if [ "$bind" -a "$bind" != '0.0.0.0' ]; then
    uci add_list fastd.mesh_vpn.bind="$bind"
fi


method="$(uci -q get fastd.mesh_vpn.method)"
uci -q delete fastd.mesh_vpn.method

if [ "$method" ]; then
    uci add_list fastd.mesh_vpn.method="$method"
fi


uci -q batch <<EOF
set fastd.mesh_vpn.interface=mesh-vpn

delete fastd.mesh_vpn.config
add_list fastd.mesh_vpn.config=/lib/freifunk/mesh-vpn/fastd.conf

delete fastd.mesh_vpn.config_peer_dir
add_list fastd.mesh_vpn.config_peer_dir=/etc/fastd/mesh-vpn/peers

commit fastd
EOF
