#!/bin/sh


(
	cd /etc/fastd/ffhl-mesh-vpn/peers
	rm -f burgtor holstentor muehlentor huextertor

	mv * /etc/fastd/mesh-vpn/peers/ 2>/dev/null || true
)

rmdir -p /etc/fastd/ffhl-mesh-vpn/peers 2>/dev/null || true
