#!/bin/sh


[ -r /etc/config/ffhl ] || exit 0

cp /etc/config/ffhl /etc/config/config_mode
mv /etc/config/ffhl /etc/config/freifunk

uci -q batch <<EOF
delete config_mode.@bandwidth[0]
commit config_mode

delete freifunk.@wizard[0]
commit freifunk
EOF

