#!/usr/bin/lua

local site = require 'gluon.site'
local util = require 'gluon.util'
local vpn_core = require 'gluon.mesh-vpn'

local uci = require('simple-uci').cursor()


local enabled

local file = '/etc/openvpn/mesh_vpn.ovpn'

-- TODO: support for directly specifying options in site conf

fd = io.open(file, 'w')
fd:write(site.mesh_vpn.openvpn.config())
fd:close()

uci:section('openvpn', 'mesh_vpn', {
	enabled = enabled,
	config = file,
	-- uuid = util.node_id(),
	-- interface = vpn_core.get_interface(),
	-- bind_interface = 'br-wan',
	-- group = 'gluon-mesh-vpn',
	-- broker_selection = 'usage',
	-- address = site.mesh_vpn.openvpn.brokers(),
})

uci:save('openvpn')
