#!/usr/bin/lua

local site = require 'gluon.site_config'
local uci = require 'luci.model.uci'

local c = uci.cursor()


c:delete('network', 'local_node_dev')
c:section('network', 'device', 'local_node_dev',
  {
    name = 'local-node',
    ifname = 'br-client',
    type = 'macvlan',
    macaddr = site.next_node.mac,
  }
)

c:delete('network', 'local_node')
c:delete('network', 'local_node4')
c:delete('network', 'local_node6')

c:section('network', 'interface', 'local_node4',
  {
    ifname = 'local-node',
    proto = 'static',
    ipaddr = site.next_node.ip4 .. '/32',
  }
)

c:section('network', 'interface', 'local_node6',
  {
    ifname = 'local-node',
    proto = 'static_deprecated',
    ip6addr = site.next_node.ip6,
  }
)

c:save('network')
c:commit('network')
