include $(TOPDIR)/rules.mk

PKG_NAME:=libgluonmath
PKG_VERSION:=1
CMAKE_INSTALL:=1

include $(INCLUDE_DIR)/package.mk

define Package/libgluonmath
  SECTION:=libs
  CATEGORY:=Libraries
  TITLE:=Gluon math library
endef

$(eval $(call BuildPackage,libgluonmath))
