override define Kernel/Configure
	$(call Kernel/Configure/Default)
	cp $(GLUONDIR)/targets/$(GLUON_TARGET)/vermagic $(LINUX_DIR)/.vermagic
endef

# The Makefile included here is $(TOPDIR)/target/linux/$(BOARD)/Makefile
include Makefile
