#!/bin/sh /etc/rc.common

START=60

USE_PROCD=1

RESOLV_CONF_DIR=/var/gluon/wan-dnsmasq
RESOLV_CONF=$RESOLV_CONF_DIR/resolv.conf

start_service() {
	mkdir -p $RESOLV_CONF_DIR
	touch "$RESOLV_CONF"

	procd_open_instance
	procd_set_param command /usr/sbin/dnsmasq \
		--user=dnsmasq \
		--group=dnsmasq \
		--interface=lo \
		--port=54 \
		--no-hosts \
		--keep-in-foreground \
		--cache-size=0 \
		--resolv-file=$RESOLV_CONF
	procd_set_param env LD_PRELOAD=libpacketmark.so LIBPACKETMARK_MARK=1
	procd_set_param respawn 60 5 5
	procd_close_instance
}
