#!/usr/bin/lua

local uci = require("simple-uci").cursor()
local wireless = require 'gluon.wireless'

wireless.foreach_radio(uci, function(radio)
	local radio_name = radio['.name']
	local suffix = radio_name:match('^radio(%d+)$')
	local name   = "wan_" .. radio_name

	if not uci:get('wireless', name, 'device') then
		return
	end

	uci:set('wireless', name, 'ifname', suffix and 'wl-wan' .. suffix)

	-- migrate encryption from Gluon v2023.2.x or older
	-- remove in 2027 or on first release supporting only upgrades from >=v2025.1.x
	local encryption = uci:get('wireless', name, 'encryption')
	uci:set('wireless', name, 'encryption', encryption:gsub("psk3", "sae"))
end)

uci:save('wireless')
