#!/bin/sh
if [ "${ACTION}" = "add" ]; then

	RAM=$(grep MemTotal /proc/meminfo |awk '{print $2}')
	if [ "$RAM" -lt $((48*1024)) ]; then
		echo "fq_memory_limit 1048576" > "/sys/kernel/debug/ieee80211/$DEVICENAME/aqm"
	fi
fi
