#!/bin/sh

if [ "${ACTION}" = 'add' ]; then
	RAM=$(awk '/MemTotal/ {print $2}' /proc/meminfo)
	if [ "$RAM" -le $((32*1024)) ]; then
		echo 'fq_memory_limit 262144' > "/sys/kernel/debug/ieee80211/$DEVICENAME/aqm"
	fi
fi
