#!/usr/bin/lua

local uci = require('simple-uci').cursor()

uci:delete('alfred', 'alfred')
uci:section('alfred', 'alfred', 'alfred', {
	interface = 'br-client',
	mode = 'slave',
	batmanif = 'bat0',
	start_vis = true,
	run_facters = false,
})

uci:save('alfred')
