#!/bin/sh /etc/rc.common

USE_PROCD=1
START=50
DAEMON=/usr/sbin/gluon-radv-filterd

start_service() {
	local threshold
	threshold="$(lua -e 'print(require("gluon.site").radv_filterd.threshold(20))')"

	procd_open_instance
	procd_set_param command "$DAEMON" -i br-client -c RADV_FILTER -t "$threshold"
	procd_set_param respawn "${respawn_threshold:-3600}" "${respawn_timeout:-5}" "${respawn_retry:-5}"
	procd_set_param netdev br-client
	procd_set_param stderr 1
	procd_close_instance
}

service_triggers() {
	procd_open_trigger
	procd_add_raw_trigger "interface.*" 1000 /etc/init.d/gluon-radv-filterd reload
	procd_close_trigger
}
