#!/usr/bin/lua

-- TODO: maybe restrict multicast to mesh?
-- TODO: userpeers with user prefix (u_) in id plus config-mode webui for that
  -- similar to static dns list field

if site.mesh.yggdrasil.enabled(false) then
  os.execute('/etc/init.d/yggdrasil enable')

  -- TODO: clear old peers (remove everything type peer, id ^s_[0-9]+)

  for index, peer in pairs(site.mesh.yggdrasil.peers({})) do
    uci:section('yggdrasil', 'peer', 's_' .. index, {
      uri = peer
    })
  end
else
  os.execute('/etc/init.d/yggdrasil disable')
end
