#!/usr/bin/lua

local sysconfig = require 'gluon.sysconfig'
local unistd = require 'posix.unistd'


if unistd.access('/lib/gluon/version/core') and not sysconfig.gluon_version then
  -- This isn't an initial upgrade, so set gluon_version
  sysconfig.gluon_version = ''
end
