#!/usr/bin/lua

local platform = require 'gluon.platform'
local sysconfig = require 'gluon.sysconfig'

local libgen = require 'posix.libgen'
local unistd = require 'posix.unistd'
local uci = require('simple-uci').cursor()

if not platform.match('x86') then
	return
end

-- Load orders (/proc/modules) of Gluon releases, oldest first - Ethernet
-- drivers only (x86-64; should be accurate enough for x86-generic as well)
-- It includes some common site-specific usb-net drivers.
local load_orders = {
	-- v2023.2.x (OpenWrt 23.05)
	{
		'tg3',
		'igb',
		'fsl_mph_dr_of',
		'ena',
		'natsemi',
		'amd_xgbe',
		'e1000',
		'ixgbe',
		'3c59x',
		'8139cp',
		'8139too',
		'8390',
		'bnx2',
		'e100',
		'e1000e',
		'forcedeth',
		'hso',
		'igc',
		'ipheth',
		'ne2k_pci',
		'pcnet32',
		'pegasus',
		'r8152',
		'r8169',
		'sis900',
		'sky2',
		'tulip',
		'via_rhine',
		'via_velocity',
		'asix',
		'ax88179_178a',
		'cdc_eem',
		'cdc_ether',
		'cdc_subset',
		'dm9601',
		'mcs7830',
		'rndis_host',
		'smsc95xx',
	},
	-- v2025.1.x (OpenWrt 24.10): igc and r8169 are loaded at boot time
	{
		'tg3',
		'igc',
		'igb',
		'fsl_mph_dr_of',
		'r8169',
		'ena',
		'natsemi',
		'amd_xgbe',
		'e1000',
		'ixgbe',
		'3c59x',
		'8139cp',
		'8139too',
		'8390',
		'bnx2',
		'e100',
		'e1000e',
		'forcedeth',
		'hso',
		'ipheth',
		'ne2k_pci',
		'pcnet32',
		'pegasus',
		'r8152',
		'sis900',
		'sky2',
		'tulip',
		'via_rhine',
		'via_velocity',
		'asix',
		'ax88179_178a',
		'cdc_eem',
		'cdc_ether',
		'cdc_subset',
		'dm9601',
		'mcs7830',
		'rndis_host',
		'smsc95xx',
	},
	-- v2026.1.x (OpenWrt 25.12): e1000e is loaded at boot time
	{
		'tg3',
		'igc',
		'igb',
		'fsl_mph_dr_of',
		'e1000e',
		'r8169',
		'ena',
		'natsemi',
		'amd_xgbe',
		'e1000',
		'ixgbe',
		'3c59x',
		'8139cp',
		'8139too',
		'8390',
		'bnx2',
		'e100',
		'forcedeth',
		'hso',
		'ipheth',
		'ne2k_pci',
		'pcnet32',
		'pegasus',
		'r8152',
		'sis900',
		'sky2',
		'tulip',
		'via_rhine',
		'via_velocity',
		'asix',
		'ax88179_178a',
		'cdc_eem',
		'cdc_ether',
		'cdc_subset',
		'dm9601',
		'mcs7830',
		'rndis_host',
		'smsc95xx',
	},
}

local current_order = #load_orders

-- Load order the roles were last aligned to ('' was written by v2025.1.x)
local prev_order = sysconfig.migrated_interface_order
if prev_order == nil then
	prev_order = 1
elseif prev_order == '' then
	prev_order = 2
else
	prev_order = tonumber(prev_order) or current_order
end

if prev_order >= current_order then
	return
end
sysconfig.migrated_interface_order = tostring(current_order)

local lan_roles = uci:get_list('gluon', 'iface_lan', 'role')
local wan_roles = uci:get_list('gluon', 'iface_wan', 'role')

if #lan_roles == 0 and #wan_roles == 0 then
	return
end

local lan_ifname = sysconfig.lan_ifname
local wan_ifname = sysconfig.wan_ifname

local function is_default(ifname)
	return ifname == 'eth0' or ifname == 'eth1'
end

if not is_default(lan_ifname) or not is_default(wan_ifname) then
	return
end

local prev_load_index = {}
for index, driver in ipairs(load_orders[prev_order]) do
	prev_load_index[driver] = index
end

local function get_prev_driver_index(ifname)
	local path = '/sys/class/net/' .. ifname .. '/device/driver'
	local driver_path = unistd.readlink(path)
	if not driver_path then
		return 0
	end
	local driver = libgen.basename(driver_path)
	local order = prev_load_index[driver]
	if not order then
		return 0
	end
	return order
end

-- If the drivers would be loaded in the inverse order in the previous Gluon
-- version (eth1 had a smaller load index than eth0), switch the roles
if get_prev_driver_index('eth0') <= get_prev_driver_index('eth1') then
	return
end

print('Switching LAN and WAN roles after module load order change')

uci:set('gluon', 'iface_lan', 'role', wan_roles)
uci:set('gluon', 'iface_wan', 'role', lan_roles)

-- Migrate VLAN interfaces
uci:foreach('gluon', 'interface', function(interface)
	local base, suffix = string.match(interface.name, '^(eth[01])(%..*)$')
	if base == 'eth0' then
		base = 'eth1'
	elseif base == 'eth1' then
		base = 'eth0'
	else
		return
	end

	uci:set('gluon', interface['.name'], 'name', base .. suffix)
end)

uci:save('gluon')
