#!/usr/bin/lua

local wireless = require 'gluon.wireless'
local uci = require('simple-uci').cursor()

local preserve_channels = wireless.preserve_channels(uci)

uci:section('gluon', 'wireless', 'wireless', {
	preserve_channels = preserve_channels or false,
})
uci:save('gluon')
