#!/usr/bin/lua

local util = require 'gluon.util'
local site = require 'gluon.site'
local sysconfig = require 'gluon.sysconfig'
local iwinfo = require 'iwinfo'

local uci = require('simple-uci').cursor()

-- Initial
if not sysconfig.gluon_version then
	uci:delete_all('wireless', 'wifi-iface')

	-- First count all radios with a fixed frequency band.
	-- This is needed to distribute devices which have radios
	-- capable of operating in the 2.4 GHz and 5 GHz band need
	-- to be distributed evenly.
	local radio_band_count = {band24=0, band5=0}
	util.foreach_radio(uci, function(radio, index, config)
		local hwmodes = iwinfo.nl80211.hwmodelist(util.find_phy(radio))
		if (hwmodes.a or hwmodes.ac) and hwmodes.g then
			-- Dualband - do nothing in this step
		elseif hwmodes.g then
			-- 2.4 GHz
			radio_band_count["band24"] = radio_band_count["band24"] + 1
		elseif hwmodes.a or hwmodes.ac then
			-- 5 GHz
			radio_band_count["band5"] = radio_band_count["band5"] + 1
		end
	end)

	-- Use the number of all fixed 2.4G GHz and 5 GHz radios to
	-- distribute dualband radios in this step.
	util.foreach_radio(uci, function(radio, index, config)
		local radio_name = radio['.name']
		local hwmodes = iwinfo.nl80211.hwmodelist(util.find_phy(radio))
		if (hwmodes.a or hwmodes.ac) and hwmodes.g then
			-- Dualband radio
			if radio_band_count["band24"] <= radio_band_count["band5"] then
				-- Assign radio to 2.4GHz band
				radio_band_count["band24"] = radio_band_count["band24"] + 1
				uci:set('wireless', radio_name, 'hwmode', '11g')
			else
				-- Assign radio to 5GHz band
				radio_band_count["band5"] = radio_band_count["band5"] + 1
				uci:set('wireless', radio_name, 'hwmode', '11a')
			end
		end
	end)
end

local function get_channel(radio, config)
	local channel
	if uci:get_first('gluon-core', 'wireless', 'preserve_channels') then
		channel = radio.channel
	end

	return channel or config.channel()
end

local function get_htmode(radio)
       local phy = util.find_phy(radio)
       if iwinfo.nl80211.hwmodelist(phy).ac then
               return 'VHT20'
       else
               return 'HT20'
       end
end

local function is_disabled(name)
	if uci:get('wireless', name) then
		return uci:get_bool('wireless', name, 'disabled')
	else
		return false
	end
end

-- Returns the first argument that is not nil; don't call without any non-nil arguments!
local function first_non_nil(first, ...)
	if first ~= nil then
		return first
	else
		return first_non_nil(...)
	end
end


local function configure_ibss(config, radio, index, suffix, disabled)
	local radio_name = radio['.name']
	local name = 'ibss_' .. radio_name

	uci:delete('network', name)
	uci:delete('network', name .. '_vlan')
	uci:delete('wireless', name)

	if not config then
		return
	end

	local macaddr = util.get_wlan_mac(uci, radio, index, 3)
	if not macaddr then
		return
	end

	if config.vlan then
		uci:section('network', 'interface', name, {
			proto = 'none',
		})

		uci:section('network', 'interface', name .. '_vlan', {
			ifname = '@' .. name .. '.' .. config.vlan,
			proto = 'gluon_mesh',
		})
	else
		uci:section('network', 'interface', name, {
			proto = 'gluon_mesh',
		})
	end

	uci:section('wireless', 'wifi-iface', name, {
		device = radio_name,
		network = name,
		mode = 'adhoc',
		ssid = config.ssid,
		bssid = config.bssid,
		macaddr = macaddr,
		mcast_rate = config.mcast_rate,
		ifname = suffix and 'ibss' .. suffix,
		disabled = disabled,
	})
end

local function configure_mesh(config, radio, index, suffix, disabled)
	local radio_name = radio['.name']
	local name = 'mesh_' .. radio_name

	local macfilter = uci:get('wireless', name, 'macfilter')
	local maclist = uci:get('wireless', name, 'maclist')

	uci:delete('network', name)
	uci:delete('network', name .. '_vlan')
	uci:delete('wireless', name)

	if not config then
		return
	end

	local macaddr = util.get_wlan_mac(uci, radio, index, 2)
	if not macaddr then
		return
	end

	uci:section('network', 'interface', name, {
		proto = 'gluon_mesh',
	})

	uci:section('wireless', 'wifi-iface', name, {
		device = radio_name,
		network = name,
		mode = 'mesh',
		mesh_id = config.id,
		mesh_fwding = false,
		macaddr = macaddr,
		mcast_rate = config.mcast_rate,
		ifname = suffix and 'mesh' .. suffix,
		disabled = disabled,
		macfilter = macfilter,
		maclist = maclist,
	})
end

local function fixup_wan(radio, index)
	local radio_name = radio['.name']
	local name = 'wan_' .. radio_name

	if not uci:get('wireless', name) then
		return
	end

	local macaddr = util.get_wlan_mac(uci, radio, index, 4)
	if not macaddr then
		return
	end

	uci:set('wireless', name, 'macaddr', macaddr)
end

util.foreach_radio(uci, function(radio, index, config)
	local radio_name = radio['.name']

	if not config() then
		uci:set('wireless', radio_name, 'disabled', true)
		return
	end

	local suffix = radio_name:match('^radio(%d+)$')
	if not suffix then
		return
	end

	local channel = get_channel(radio, config)
	local htmode = get_htmode(radio)

	uci:delete('wireless', radio_name, 'disabled')

	uci:set('wireless', radio_name, 'channel', channel)
	uci:set('wireless', radio_name, 'htmode', htmode)
	uci:set('wireless', radio_name, 'country', site.regdom())

	local hwmode = radio.hwmode
	if hwmode == '11g' or hwmode == '11ng' then
		uci:set('wireless', radio_name, 'legacy_rates', false)
	end

	uci:delete('wireless', radio_name, 'supported_rates')
	uci:delete('wireless', radio_name, 'basic_rate')

	local ibss_disabled = is_disabled('ibss_' .. radio_name)
	local mesh_disabled = is_disabled('mesh_' .. radio_name)

	configure_ibss(config.ibss(), radio, index, suffix,
		first_non_nil(
			ibss_disabled,
			mesh_disabled,
			config.ibss.disabled(false)
		)
	)
	configure_mesh(config.mesh(), radio, index, suffix,
		first_non_nil(
			mesh_disabled,
			ibss_disabled,
			config.mesh.disabled(false)
		)
	)

	fixup_wan(radio, index)
end)


if uci:get('system', 'rssid_wlan0') then
	if uci:get('wireless', 'mesh_radio0') then
		uci:set('system', 'rssid_wlan0', 'dev', 'mesh0')
	else
		uci:set('system', 'rssid_wlan0', 'dev', 'ibss0')
	end

	uci:save('system')
end

uci:save('wireless')
uci:save('network')
