#!/usr/bin/lua

local util = require 'gluon.util'
local wireless = require 'gluon.wireless'
local site = require 'gluon.site'
local iwinfo = require 'iwinfo'

local uci = require('simple-uci').cursor()

if not uci:get_bool('gluon', 'wireless', 'preserve_channels') then
	uci:delete_all('wireless', 'wifi-iface')
end

local radio_band_count = {band2g=0, band5g=0}

local function count_band(band)
	radio_band_count[band] = radio_band_count[band] + 1
end

-- First count all radios with a fixed frequency band.
-- This is needed to distribute devices which have radios
-- capable of operating in the 2.4 GHz and 5 GHz band need
-- to be distributed evenly.
wireless.foreach_radio(uci, function(radio)
	local hwmodes = iwinfo.nl80211.hwmodelist(wireless.find_phy(radio))
	if hwmodes.g and not (hwmodes.a or hwmodes.ac) then
		-- 2.4 GHz
		count_band("band2g")
	elseif (hwmodes.a or hwmodes.ac) and not hwmodes.g then
		-- 5 GHz
		count_band("band5g")
	end
end)

-- Use the number of all fixed 2.4G GHz and 5 GHz radios to
-- distribute dualband radios in this step.
wireless.foreach_radio(uci, function(radio)
	local radio_name = radio['.name']
	local hwmodes = iwinfo.nl80211.hwmodelist(wireless.find_phy(radio))
	if (hwmodes.a or hwmodes.ac) and hwmodes.g then
		-- Dualband radio
		if radio_band_count["band2g"] <= radio_band_count["band5g"] then
			-- Assign radio to 2.4GHz band
			count_band("band2g")
			uci:set('wireless', radio_name, 'band', '2g')
		else
			-- Assign radio to 5GHz band
			count_band("band5g")
			uci:set('wireless', radio_name, 'band', '5g')
		end
	end
end)

local function is_outdoor()
	return uci:get_bool('gluon', 'wireless', 'outdoor')
end

local function get_channel(radio, config)
	if radio.band == '5g' and is_outdoor() then
		-- actual channel will be picked and probed from chanlist
		return 'auto'
	end

	return config.channel()
end

local function get_htmode(radio)
	if wireless.preserve_channels(uci) then
		return radio.htmode
	end

	if radio.band == '5g' and is_outdoor() then
		local outdoor_htmode = uci:get('gluon', 'wireless', 'outdoor_' .. radio['.name'] .. '_htmode')
		if outdoor_htmode ~= nil then
			return outdoor_htmode
		end
	end

	local phy = wireless.find_phy(radio)
	if iwinfo.nl80211.hwmodelist(phy).ax then
		return 'HE20'
	end

	if iwinfo.nl80211.hwmodelist(phy).ac then
		return 'VHT20'
	end

	return 'HT20'
end

-- Returns the first argument that is not nil; don't call without any non-nil arguments!
local function first_non_nil(first, ...)
	if first ~= nil then
		return first
	end

	return first_non_nil(...)
end


local function delete_ibss(radio_name)
	local name = 'ibss_' .. radio_name

	uci:delete('wireless', name)
end

local function configure_mesh(config, radio, index, suffix, disabled)
	local radio_name = radio['.name']
	local name = 'mesh_' .. radio_name

	local macfilter = uci:get('wireless', name, 'macfilter')
	local maclist = uci:get('wireless', name, 'maclist')

	uci:delete('wireless', name)

	if not config then
		return
	end

	local macaddr = wireless.get_wlan_mac('mesh', index, radio)
	if not macaddr then
		return
	end

	local batadv_hop_penalty = uci:get('gluon', radio.band, 'batadv_hop_penalty') or 0

	uci:section('network', 'interface', name, {
		proto = 'gluon_mesh',
		hop_penalty = batadv_hop_penalty,
	})

	uci:section('wireless', 'wifi-iface', name, {
		device = radio_name,
		network = name,
		mode = 'mesh',
		mesh_id = config.id,
		mesh_fwding = false,
		mesh_nolearn = true,
		macaddr = macaddr,
		basic_rate = { config.mcast_rate },
		mcast_rate = config.mcast_rate,
		ifname = suffix and 'mesh' .. suffix,
		disabled = disabled,
		macfilter = macfilter,
		maclist = maclist,
	})
end

local function configure_mesh_wireless(radio, index, config, disabled)
	local radio_name = radio['.name']
	local suffix = radio_name:match('^radio(%d+)$')

	configure_mesh(config.mesh(), radio, index, suffix,
		first_non_nil(
			disabled,
			config.mesh.disabled(false)
		)
	)
end

local function set_channels(radio, radio_name, config)
	if wireless.preserve_channels(uci) then
		return
	end
	local channel = get_channel(radio, config)
	uci:set('wireless', radio_name, 'channel', channel)

	local chanlist
	if radio.band == '5g' and is_outdoor() then
		chanlist = config.outdoor_chanlist()
	end
	uci:set('wireless', radio_name, 'channels', chanlist)
end

wireless.foreach_radio(uci, function(radio, index, config)
	local radio_name = radio['.name']

	delete_ibss(radio_name)

	if not config() then
		uci:set('wireless', radio_name, 'disabled', true)
		return
	end

	local suffix = radio_name:match('^radio(%d+)$')
	if not suffix then
		return
	end

	local htmode = get_htmode(radio)
	local beacon_interval = config.beacon_interval()

	uci:delete('wireless', radio_name, 'disabled')

	set_channels(radio, radio_name, config)

	uci:set('wireless', radio_name, 'htmode', htmode)
	uci:set('wireless', radio_name, 'country', site.regdom())

	uci:delete('wireless', radio_name, 'supported_rates')
	uci:delete('wireless', radio_name, 'basic_rate')

	local band = radio.band
	-- now we assign radios to roles
	local roles = uci:get('gluon', band, 'role')

	if band == '2g' then
		uci:set('wireless', radio_name, 'legacy_rates', false)
	end

	if roles and util.contains(roles, 'mesh') then
		if band == '2g' then
			configure_mesh_wireless(radio, index, config, false)
		elseif (band == '5g') then
			if is_outdoor() or not wireless.supports_channel(radio, config.channel()) then
				-- enforce outdoor channels by filtering the regdom for outdoor channels
				uci:set('wireless', radio_name, 'country3', '0x4f')
				configure_mesh_wireless(radio, index, config, true)
			else
				uci:delete('wireless', radio_name, 'country3')
				configure_mesh_wireless(radio, index, config, false)
			end
		end
	else
		-- disable mesh if role is not configured
		configure_mesh_wireless(radio, index, config, true)
	end

	uci:set('wireless', radio_name, 'beacon_int', beacon_interval)
end)


if uci:get('system', 'rssid_wlan0') then
	uci:set('system', 'rssid_wlan0', 'dev', 'mesh0')
	uci:save('system')
end

if uci:get('system', 'rssid_wlan1') then
	uci:set('system', 'rssid_wlan1', 'dev', 'mesh1')
	uci:save('system')
end

uci:save('wireless')
uci:save('network')
