#!/usr/bin/lua

local site = require 'gluon.site'
local uci = require('simple-uci').cursor()
local util = require 'gluon.util'

local mesh_interfaces = util.get_role_interfaces_with_options(uci, 'mesh', {'batadv_hop_penalty'})
local uplink_interfaces = util.get_role_interfaces_with_options(uci, 'uplink', {'batadv_hop_penalty'})

local mesh_interfaces_uplink = {}
local mesh_interfaces_other = {}
for iface, options in pairs(mesh_interfaces) do
	if uplink_interfaces[iface] ~= nil then
		mesh_interfaces_uplink[iface] = options
	else
		mesh_interfaces_other[iface] = options
	end
end

local function extract_ifaces(interfaces)
	local ifnames = {}
	local if_count = 0
	local max_hop_penalty = 0
	for ifname, options in pairs(interfaces) do
		table.insert(ifnames, ifname)
		if_count = if_count + 1
		if options['batadv_hop_penalty'] and tonumber(options['batadv_hop_penalty']) > max_hop_penalty then
			max_hop_penalty = options['batadv_hop_penalty']
		end
	end
	return max_hop_penalty, ifnames, if_count
end

if next(mesh_interfaces_uplink) ~= nil then
	local max_hop_penalty, _, _ = extract_ifaces(mesh_interfaces_uplink)
	uci:section('network', 'interface', 'mesh_uplink', {
		ifname = 'br-wan',
		proto = 'gluon_wired',
		func = 'wan',
		hop_penalty = max_hop_penalty,
		vxlan = site.mesh.vxlan(true),
	})
end

if next(mesh_interfaces_other) ~= nil then
	local max_hop_penalty, ifnames, if_count = extract_ifaces(mesh_interfaces_other)
	local iftype, ifname
	if if_count == 1 then
		ifname = ifnames[1]
	else
		iftype = 'bridge'
		ifname = ifnames

		for _, iface in ipairs(ifname) do
			uci:section('network', 'device', nil, {
				name = iface,
				isolate = true,
			})
		end

	end

	uci:section('network', 'interface', 'mesh_other', {
		ifname = ifname,
		type = iftype,
		igmp_snooping = false,
		proto = 'gluon_wired',
		func = 'mesh_other',
		hop_penalty = max_hop_penalty,
		vxlan = site.mesh.vxlan(true),
	})
end

uci:save('network')
