#!/usr/bin/lua

local site = require 'gluon.site'
local sysconfig = require 'gluon.sysconfig'

local uci = require('simple-uci').cursor()

if not sysconfig.lan_ifname then
	os.exit(0)
end

local type
if sysconfig.lan_ifname:match(' ') then
	type = 'bridge'
end

local disabled = uci:get('network_gluon-old', 'mesh_lan', 'disabled')
if disabled == nil then
	disabled = not site.mesh_on_lan(false)
end

local transitive = uci:get('network_gluon-old', 'mesh_lan', 'transitive')
if transitive == nil then
	transitive = true
end

uci:section('network', 'interface', 'mesh_lan', {
	ifname = sysconfig.lan_ifname,
	type = type,
	igmp_snooping = false,
	proto = 'gluon_wired',
	index = 4,
	vxlan = site.mesh.vxlan(true),
	disabled = disabled,
	transitive = transitive,
})

uci:save('network')
