#!/usr/bin/lua

local util = require "gluon.util"
local unistd = require "posix.unistd"

if util.get_mem_total() >= 64 * 1024 * 1024 then
	return
end

unistd.link(
	"/lib/gluon/sysctl/memory-64m.sysctl",
	"/etc/sysctl.d/35-gluon-memory-64m.sysctl",
	true)
