#!/usr/bin/lua

local uci = require 'luci.model.uci'

local c = uci.cursor()

local secret = c:get("fastd", "mesh_vpn", "secret")

if not secret or not secret:match(("%x"):rep(64)) then
  c:set("fastd", "mesh_vpn", "secret", "generate")
  c:save("fastd")
end
