pipeline {
	agent none
	environment {
		GLUON_SITEDIR = "contrib/ci/minimal-site"
		GLUON_TARGET = "x86-64"
		BUILD_LOG = "1"
	}
	stages {
		stage('lint') {
			parallel {
				stage('lint-lua') {
					agent { label 'gluon-docker' }
					steps {
						sh 'make lint-lua'
					}
				}
				stage('lint-sh') {
					agent { label 'gluon-docker' }
					steps {
						sh 'make lint-sh'
					}
				}
			}
		}
		stage('docs') {
			agent { label 'gluon-docker' }
			steps {
				sh 'make -C docs html'
			}
		}
		stage('build') {
			agent { label 'gluon-docker' }
			steps {
				sh 'make update'
				sh 'test -d /dl_cache && ln -s /dl_cache openwrt/dl || true'
				sh 'make -j$(nproc) V=s'
			}
		}
	}
}
