include $(TOPDIR)/rules.mk

PKG_NAME:=gluon-web-osm
PKG_VERSION:=1

include ../gluon.mk

define Package/gluon-web-osm
  TITLE:=base src for OSM inlay
endef

$(eval $(call BuildPackageGluon,gluon-web-osm))
