#!/bin/sh

. /lib/gluon/functions/sysconfig.sh
. /lib/ar71xx.sh


sysconfig_isset config_ifname && exit 0


case "$(ar71xx_board_name)" in
	nanostation-m)
		sysconfig_set config_ifname "$(sysconfig wan_ifname || sysconfig lan_ifname)"
		;;
	*)
		sysconfig_set config_ifname "$(sysconfig lan_ifname || sysconfig wan_ifname)"
		;;
esac
