#!/bin/sh


. /lib/functions.sh
. /lib/gluon/functions/sysconfig.sh


uci_rename network '@legacy.mesh_ifname@' 'client'

uci_remove network client auto
uci_remove network client accept_ra

uci_set network client proto 'dhcpv6'
uci_set network client reqprefix 'no'

uci_commit network
