#!/bin/sh


wait=3


wait_setup_mode() {
	sleep $wait
	/lib/gluon/setup-mode/led.sh confirm
	gluon-enter-setup-mode
}

# Special case for devices that use capacitive buttons
case "$(board_name)" in
genexis,pulse-ex400)
	[ "$BUTTON" = wps ] && exit 0
	;;
esac

if [ "$BUTTON" = wps ] || [ "$BUTTON" = reset ] || [ "$BUTTON" = phone ]; then
	case "$ACTION" in
		pressed)
			wait_setup_mode &
			PID=$!
			echo $PID > /tmp/.wait_setup_mode
			;;
		released)
			if [ -r /tmp/.wait_setup_mode ]; then
				kill "$(cat /tmp/.wait_setup_mode)"
				rm /tmp/.wait_setup_mode
			fi
			;;
	esac
fi
