#!/usr/bin/lua

local uci = require('luci.model.uci').cursor()

-- Allow announced port on WAN to allow resolving neighbours over mesh-on-wan
uci:section('firewall', 'rule', 'wan_announced',
  {
    name = 'wan_announced',
    src = 'wan',
    src_ip = 'fe80::/64',
    dest_port = '1001',
    proto = 'udp',
    target = 'ACCEPT',
  }
)

uci:save('firewall')
uci:commit('firewall')
